//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointsTradingDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string ProductOldPrice { get; set; }
        public string ProductImageURL { get; set; }
        public string ProductDescription { get; set; }
        public string ProductVideo { get; set; }
        public int ProductCategoryID { get; set; }
        public Nullable<bool> IsLatestProduct { get; set; }
    }
}
